# Generated by Django 2.2.8 on 2021-04-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='admission_date',
            field=models.DateTimeField(),
        ),
    ]
