# Generated by Django 2.2.8 on 2021-04-19 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20210417_1739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentinfo',
            options={'permissions': (('can delete student info', 'Set student been delete'),)},
        ),
    ]
