# Generated by Django 2.2.8 on 2021-04-19 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20210420_0056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentinfo',
            options={},
        ),
    ]
